### ISSUE TITLE
Lidar Data

### ISSUE THREAD

**Issue by Ygarr** [pauldpickell/gis2minetest#1]
Is this data available for every locations in OSM?

**Comment by pauldpickell** [comment]
You need to provide LiDAR data independently. The script will grab the OSM data for the coordinates that correspond to the area you want to map within your LiDAR point cloud.

**Comment by Ygarr** [comment]
So, there could be an obstacle in the form of finding LiDAR data for a specific location..

**Comment by pauldpickell** [comment]
Yes, this script will only work for areas where LiDAR data exist. There is no central repository to grab LiDAR data from, so you need to provide your own.

**Comment by Ygarr** [comment]
thanks it`s saved my time.
